"use client"
import Link from "next/link"
import { AlertCircle, ArrowUpRight, Building2, Check, Clock3, Info, Loader2, Mail } from "lucide-react"

export function ApplicationStatus({ phase, institution, email, retry }: { phase: "verify" | "success" | "received" | "invalid" | "network" | "loading"; institution?: string; email?: string; retry?: () => void }) {
  const success = phase === "success"
  const waiting = phase === "verify"
  const received = phase === "received"
  const error = phase === "invalid" || phase === "network"
  return <section className="ref-application-status"><nav aria-label="Başvuru aşaması"><Link href="/kurum-kaydi">Kurum Kaydı</Link><span>/</span><strong>{received ? "Başvuru Durumu" : "E-posta Doğrulama"}</strong></nav><div className="ref-status-content" aria-live="polite"><div className={`ref-mail-symbol ${error ? "ref-mail-error" : waiting ? "ref-mail-waiting" : ""}`}>{phase === "loading" ? <Loader2 className="animate-spin" /> : error ? <AlertCircle /> : <><Mail />{success && <i><Check /></i>}</>}</div><h1>{received ? "Başvurunuz alındı." : success ? "E-posta adresiniz doğrulandı." : waiting ? "E-posta adresinizi doğrulayın." : phase === "loading" ? "Adresiniz doğrulanıyor." : phase === "network" ? "Bağlantı kurulamadı." : "Bağlantıyı kontrol edelim."}</h1><p>{received ? "Başvurunuz platform yönetimine iletildi. Onay sonucu ve uygulama giriş bilgileriniz e-posta ile bildirilecek." : success ? "Başvurunuz incelemeye alındı. Onay sonucu e-posta ile bildirilecek." : waiting ? "Başvurunuz alındı. E-postanızdaki bağlantıya tıklayarak adresinizi doğrulayın." : phase === "loading" ? "Lütfen kısa bir süre bekleyin." : phase === "network" ? "Sunucuya şu anda ulaşılamıyor. Bu sekmeden yeniden deneyebilirsiniz." : "Doğrulama bağlantısı geçersiz veya süresi dolmuş olabilir. Aynı e-posta adresiyle yeniden başvurabilirsiniz."}</p>
  {(success || waiting || received) && <><div className="ref-application-steps">{["Kurum kaydı", received ? "Başvuru incelemesi" : "E-posta doğrulama", "Yönetici onayı"].map((label, index) => <div key={label} className={index === 0 || index === 1 && success ? "complete" : "waiting"}><b>{index === 0 || index === 1 && success ? <Check /> : <Clock3 />}</b><strong>{label}</strong><p>{index === 0 || index === 1 && success ? "Tamamlandı" : "Bekleniyor"}</p></div>)}</div><div className="ref-approval-badge"><Clock3 size={20} />{success || received ? "Onay bekliyor" : "Doğrulama bekliyor"}</div><div className="ref-application-info"><div><Building2 /><span><strong>{institution || "Kurum başvurunuz"}</strong><p>{email || "E-posta adresiniz doğrulandı."}</p></span></div><div><Info /><p>Kurumunuz onaylandıktan sonra<br />masaüstü ve mobil uygulama giriş bilgileriniz paylaşılacak.</p></div></div></>}
  {phase !== "loading" && <div className="sa-actions">{phase === "network" ? <button className="sa-button" onClick={retry}>Yeniden dene</button> : phase === "invalid" ? <Link className="sa-button" href="/kurum-kaydi">Yeniden başvur</Link> : <Link className="ref-outline-button" href="/">Ana sayfaya dön</Link>}<Link className="sa-button" href={error ? "/iletisim" : "/destek"}>{error ? "Bize ulaşın" : "Destek sayfası"} <ArrowUpRight size={18} /></Link></div>}</div></section>
}
