import { useCallback, useEffect, useMemo, useState } from 'react';
import { Archive, CheckCircle2, Download, FilePlus2, RefreshCw, ShieldCheck, XCircle } from 'lucide-react';
import { Badge } from '../../components/ui/badge';
import { Button } from '../../components/ui/button';
import { useToast } from '../../hooks/use-toast';
import { createDrivingTransferPackage, downloadDrivingTransferPackage, fetchDrivingTransferPackages, updateDrivingTransferPackageStatus } from '../../lib/api/modules';
import { DRIVING, useDrivingPermissions } from '../../lib/drivingPermissions';
import { DrivingLoading, DrivingNotice, DrivingPage, DrivingPageHeader, DrivingStatCard } from './_shared';

const TYPES = { CandidateRegistration: 'Aday kayıt paketi', TermStudentList: 'Dönem kursiyer listesi', TheorySchedule: 'Teorik ders programı', DrivingSchedule: 'Direksiyon ders programı', ExamCandidateList: 'Sınav aday listesi', ExamResultList: 'Sınav sonuç listesi', CertificateList: 'Sertifika listesi', InvoiceList: 'Fatura listesi', MeisStatistics: 'MEİS istatistik paketi' };
const STATUS = { Generated: ['Oluşturuldu', 'bg-blue-500/15 text-blue-700'], Transferred: ['Aktarıldı', 'bg-emerald-500/15 text-emerald-700'], Failed: ['Hatalı', 'bg-red-500/15 text-red-700'], Cancelled: ['İptal', 'bg-slate-500/15 text-slate-700'] };

export default function DrivingTransferPackages() {
  const { can } = useDrivingPermissions(); const canCreate = can(DRIVING.mebbisManage) && can(DRIVING.reportExport); const canDownload = can(DRIVING.reportView); const canManage = can(DRIVING.mebbisManage);
  const { toast } = useToast(); const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState('');
  const [form, setForm] = useState({ studentGroupId: '', packageType: 'CandidateRegistration' });
  const load = useCallback(async () => { setLoading(true); try { const value = await fetchDrivingTransferPackages(); setData(value); setForm((x) => ({ ...x, studentGroupId: x.studentGroupId || value.groups?.find((g) => g.isActive)?.id || value.groups?.[0]?.id || '' })); } catch (e) { toast({ title: 'Aktarım paketleri alınamadı', description: e.message, variant: 'destructive' }); } finally { setLoading(false); } }, [toast]);
  useEffect(() => { load(); }, [load]);
  const items = data?.items || []; const counts = useMemo(() => ({ generated: items.filter((x) => x.status === 'Generated').length, transferred: items.filter((x) => x.status === 'Transferred').length, failed: items.filter((x) => x.status === 'Failed').length }), [items]);
  const create = async () => { if (!form.studentGroupId) return; setSaving('create'); try { await createDrivingTransferPackage(form); toast({ title: 'Yeni sürüm güvenli arşive kaydedildi' }); await load(); } catch (e) { toast({ title: 'Paket oluşturulamadı', description: e.message, variant: 'destructive' }); } finally { setSaving(''); } };
  const download = async (item) => { setSaving(item.id); try { const blob = await downloadDrivingTransferPackage(item.id); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = item.fileName; anchor.click(); URL.revokeObjectURL(url); } catch (e) { toast({ title: 'Dosya indirilemedi', description: e.message, variant: 'destructive' }); } finally { setSaving(''); } };
  const status = async (item, target) => { setSaving(item.id); try { await updateDrivingTransferPackageStatus(item.id, { status: target, errorResult: '', expectedVersion: item.statusVersion }); await load(); toast({ title: 'Aktarım durumu güncellendi' }); } catch (e) { toast({ title: 'Durum güncellenemedi', description: e.message, variant: 'destructive' }); } finally { setSaving(''); } };
  if (loading && !data) return <DrivingLoading />;
  return <DrivingPage testId="driving-transfer-packages-page">
    <DrivingPageHeader title="MEBBİS Aktarım Paketleri" description="Dönem çıktılarının değiştirilemeyen, sürümlü ve bütünlük doğrulamalı arşivi." icon={Archive} onRefresh={load} />
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><DrivingStatCard label="Toplam paket" value={data?.total || 0} caption="Arşiv kaydı" icon={Archive} tone="brand" /><DrivingStatCard label="Aktarım bekleyen" value={counts.generated} caption="Oluşturuldu" icon={FilePlus2} tone="blue" /><DrivingStatCard label="Aktarıldı" value={counts.transferred} caption="Tamamlandı" icon={CheckCircle2} tone="emerald" /><DrivingStatCard label="Hatalı" value={counts.failed} caption="İncelenmeli" icon={XCircle} tone="rose" /></div>
    <div className="grid gap-3 rounded-2xl border p-4 md:grid-cols-[1fr_1fr_auto]">
      <label className="space-y-1 text-sm font-medium"><span>Dönem</span><select className="h-10 w-full rounded-md border bg-background px-3" value={form.studentGroupId} onChange={(e) => setForm((x) => ({ ...x, studentGroupId: e.target.value }))}><option value="">Dönem seçin</option>{(data?.groups || []).map((g) => <option key={g.id} value={g.id}>{g.name} · {g.termYear || '—'}/{g.termNumber || '—'}</option>)}</select></label>
      <label className="space-y-1 text-sm font-medium"><span>Paket türü</span><select className="h-10 w-full rounded-md border bg-background px-3" value={form.packageType} onChange={(e) => setForm((x) => ({ ...x, packageType: e.target.value }))}>{Object.entries(TYPES).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>
      <Button className="self-end" disabled={!canCreate || !form.studentGroupId || saving === 'create'} onClick={create}><FilePlus2 className="mr-2 h-4 w-4" />Yeni sürüm oluştur</Button>
    </div>
    {items.length === 0 ? <DrivingNotice icon={Archive} title="Henüz aktarım paketi yok" message="Dönem ve paket türünü seçerek ilk sürümü oluşturun." /> : <div className="space-y-3">{items.map((item) => { const state = STATUS[item.status] || [item.status, '']; return <article key={item.id} className="rounded-2xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><b>{TYPES[item.packageType] || item.packageType}</b><Badge className={`border-0 ${state[1]}`}>{state[0]}</Badge><Badge variant="outline">v{item.fileVersion}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{item.termYear || '—'}/{item.termNumber || '—'} · {item.mebbisTermCode || 'Kod yok'} · {new Date(item.createdAtUtc).toLocaleString('tr-TR')} · {item.createdByName}</p><p className="mt-1 text-xs text-muted-foreground">{item.studentCount} kursiyer · {item.rowCount} satır · {(item.fileSize / 1024).toFixed(1)} KB · SHA-256: {item.sha256.slice(0, 12)}…</p></div><div className="flex flex-wrap gap-2">{canDownload && <Button size="sm" variant="outline" disabled={saving === item.id} onClick={() => download(item)}><Download className="mr-2 h-4 w-4" />İndir</Button>}{canManage && item.status === 'Generated' && <Button size="sm" disabled={saving === item.id} onClick={() => status(item, 'Transferred')}><ShieldCheck className="mr-2 h-4 w-4" />Aktarıldı</Button>}</div></div>{item.errorResult && <p className="mt-3 rounded-xl bg-red-500/10 p-3 text-sm text-red-700"><b>Hata sonucu:</b> {item.errorResult}</p>}</article>; })}</div>}
  </DrivingPage>;
}
