import { useCallback, useEffect, useMemo, useState } from 'react';
import { Award, ShieldCheck, Upload } from 'lucide-react';
import { Badge } from '../../components/ui/badge';
import { Button } from '../../components/ui/button';
import { useToast } from '../../hooks/use-toast';
import { applyDrivingMebbisImport, fetchDrivingMebbisCertificateNumber, fetchDrivingMebbisCertificateNumbers, previewDrivingMebbisImport } from '../../lib/api/modules';
import { DRIVING, useDrivingPermissions } from '../../lib/drivingPermissions';
import { DrivingLoading, DrivingNotice, DrivingPage, DrivingPageHeader } from './_shared';
import { formatDateTime } from '../../lib/format';

const LABELS = { Change: 'İşlenecek', Unchanged: 'Zaten aynı', Conflict: 'Mükerrer/çelişki', NotFound: 'Bulunamadı', Invalid: 'Geçersiz' };

export default function DrivingMebbisCertificateNumbers() {
  const { toast } = useToast(); const { can } = useDrivingPermissions();
  const [data, setData] = useState(null); const [detail, setDetail] = useState(null); const [groupId, setGroupId] = useState(''); const [file, setFile] = useState(null); const [excluded, setExcluded] = useState(() => new Set()); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const value = await fetchDrivingMebbisCertificateNumbers(); setData(value); setGroupId((old) => old || value.groups?.find((x) => x.isActive)?.id || value.groups?.[0]?.id || ''); } catch (e) { toast({ title: 'Sertifika aktarımları alınamadı', description: e.message, variant: 'destructive' }); } finally { setLoading(false); } }, [toast]);
  useEffect(() => { load(); }, [load]);
  const open = async (id) => { setSaving(true); try { setDetail(await fetchDrivingMebbisCertificateNumber(id, { pageSize: 500 })); setExcluded(new Set()); } catch (e) { toast({ title: 'Önizleme açılamadı', description: e.message, variant: 'destructive' }); } finally { setSaving(false); } };
  const preview = async () => { if (!file || !groupId) return; if (file.size > 5 * 1024 * 1024) return toast({ title: 'Dosya 5 MB sınırını aşıyor', variant: 'destructive' }); const form = new FormData(); form.append('file', file); form.append('importType', 'CertificateNumbers'); form.append('studentGroupId', groupId); setSaving(true); try { const result = await previewDrivingMebbisImport(form); await load(); await open(result.id); toast({ title: 'Güvenli önizleme hazır', description: 'Henüz hiçbir sertifika değiştirilmedi.' }); } catch (e) { toast({ title: 'Dosya analiz edilemedi', description: e.message, variant: 'destructive' }); } finally { setSaving(false); } };
  const apply = async () => { const session = detail?.session; if (!session) return; setSaving(true); try { const result = await applyDrivingMebbisImport(session.id, { expectedPreviewVersion: session.previewVersion, excludedRowIds: [...excluded], createRetryFees: false }); toast({ title: `${result.applied} sertifika numarası işlendi` }); await load(); await open(session.id); } catch (e) { toast({ title: 'Numaralar uygulanamadı', description: e.message, variant: 'destructive' }); } finally { setSaving(false); } };
  const rows = detail?.rows || []; const actionable = useMemo(() => rows.filter((x) => x.canApply), [rows]);
  if (loading && !data) return <DrivingLoading />;
  const summary = detail?.summary || {}; const session = detail?.session;
  return <DrivingPage testId="driving-mebbis-certificate-numbers-page">
    <DrivingPageHeader title="Sertifika Numarası Toplu Aktarımı" description="MEBBİS sertifika listesini TC kimlik veya kursiyer numarasıyla eşleştirin; mükerrerleri engelleyip yalnız onaylanan satırları işleyin." icon={Award} onRefresh={load} />
    <div className="grid gap-3 rounded-2xl border p-4 lg:grid-cols-[1fr_1.4fr_auto]">
      <label className="space-y-1 text-sm font-medium"><span>Dönem</span><select className="h-10 w-full rounded-md border bg-background px-3" value={groupId} onChange={(e) => setGroupId(e.target.value)}><option value="">Dönem seçin</option>{(data?.groups || []).map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
      <label className="space-y-1 text-sm font-medium"><span>MEBBİS CSV/XLSX · TC/Kursiyer No + Sertifika No</span><input type="file" accept=".csv,.xlsx" className="block h-10 w-full rounded-md border p-1.5 text-sm" onChange={(e) => setFile(e.target.files?.[0] || null)} /></label>
      <Button className="self-end" disabled={!can(DRIVING.mebbisManage) || !file || !groupId || saving} onClick={preview}><Upload className="mr-2 h-4 w-4" />Güvenli önizleme</Button>
    </div>
    {session && <section className="space-y-4 rounded-2xl border p-4">
      <div className="flex flex-wrap justify-between gap-3"><div><b>{session.fileName}</b><p className="text-xs text-muted-foreground">{session.status} · önizleme v{session.previewVersion}</p></div>{session.status === 'PreviewReady' && <Button disabled={!can(DRIVING.mebbisVerify) || !can(DRIVING.graduationManage) || saving || actionable.length === excluded.size} onClick={apply}><ShieldCheck className="mr-2 h-4 w-4" />Seçilenleri toplu onayla</Button>}</div>
      <div className="grid grid-cols-2 gap-2 md:grid-cols-7"><Mini label="Toplam" value={summary.total} /><Mini label="İşlenecek" value={summary.toUpdate} /><Mini label="Aynı" value={summary.unchanged} /><Mini label="Mükerrer" value={summary.duplicates} danger /><Mini label="Kişi yok" value={summary.missingPeople} danger /><Mini label="Sertifika yok" value={summary.missingCertificates} danger /><Mini label="Geçersiz" value={summary.invalid} danger /></div>
      <div className="max-h-[620px] overflow-auto rounded-xl border"><table className="w-full min-w-[980px] text-left text-sm"><thead className="sticky top-0 bg-background"><tr><th className="p-3">Uygula</th><th>Kursiyer</th><th>Eşleşme</th><th>Belge</th><th>Mevcut MEBBİS No</th><th>Yeni MEBBİS No</th><th>Durum</th></tr></thead><tbody>{rows.map((row) => <tr key={row.rowId} className="border-t"><td className="p-3"><input type="checkbox" disabled={!row.canApply || session.status !== 'PreviewReady'} checked={row.canApply && !excluded.has(row.rowId)} onChange={() => setExcluded((old) => { const next = new Set(old); next.has(row.rowId) ? next.delete(row.rowId) : next.add(row.rowId); return next; })} /></td><td className="py-3 pr-3"><b>{row.name || 'Bulunamadı'}</b><div className="text-xs text-muted-foreground">{row.studentNumber || 'Kursiyer no yok'}</div></td><td className="py-3 pr-3 font-mono text-xs">{row.maskedMatchKey}</td><td className="py-3 pr-3">{row.documentNumber || '—'}</td><td className="py-3 pr-3 font-mono">{row.currentMebbisNumber || '—'}</td><td className="py-3 pr-3 font-mono font-bold">{row.incomingMebbisNumber || '—'}</td><td className="py-3 pr-3"><Badge variant={row.duplicate ? 'destructive' : 'outline'}>{LABELS[row.classification] || row.classification}</Badge>{row.messages?.length > 0 && <p className="mt-1 max-w-[250px] text-xs text-muted-foreground">{row.messages.join(' ')}</p>}</td></tr>)}</tbody></table></div>
    </section>}
    <div className="space-y-3"><h2 className="font-bold">Aktarım geçmişi</h2>{(data?.imports || []).length === 0 ? <DrivingNotice icon={Award} title="Henüz aktarım yok" message="MEBBİS sertifika listesinden güvenli önizleme oluşturun." /> : data.imports.map((x) => <button type="button" key={x.id} onClick={() => open(x.id)} className="flex w-full items-center justify-between rounded-2xl border p-4 text-left"><div><b>{x.fileName}</b><p className="text-xs text-muted-foreground">{x.totalRows} satır · {formatDateTime(x.createdAtUtc)} · {x.createdByName}</p></div><Badge variant="outline">{x.status}</Badge></button>)}</div>
  </DrivingPage>;
}
function Mini({ label, value, danger }) { return <div className={`rounded-xl border p-3 ${danger && value ? 'border-red-300 bg-red-500/5' : ''}`}><p className="text-xs text-muted-foreground">{label}</p><b className="text-xl">{value || 0}</b></div>; }
