import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, FileInput, RefreshCw, ShieldCheck, Upload, XCircle } from 'lucide-react';
import { Badge } from '../../components/ui/badge';
import { Button } from '../../components/ui/button';
import { useToast } from '../../hooks/use-toast';
import { applyDrivingMebbisImport, fetchDrivingMebbisImport, fetchDrivingMebbisImports, previewDrivingMebbisImport, rejectDrivingMebbisImport } from '../../lib/api/modules';
import { DRIVING, useDrivingPermissions } from '../../lib/drivingPermissions';
import { DrivingLoading, DrivingNotice, DrivingPage, DrivingPageHeader, DrivingStatCard } from './_shared';

const TYPES = { CandidateList: 'MEBBİS aday listesi', ExamResults: 'Sınav sonuçları', CertificateNumbers: 'Sertifika numaraları', TermList: 'Dönem listesi', StudentStatuses: 'Kursiyer durumları' };
const CLASSES = { Matched: ['Eşleşti', 'bg-blue-500/15 text-blue-700'], NotFound: ['Bulunamadı', 'bg-slate-500/15 text-slate-700'], Conflict: ['Çelişki', 'bg-red-500/15 text-red-700'], Change: ['Değişecek', 'bg-amber-500/15 text-amber-700'], New: ['Yeni', 'bg-violet-500/15 text-violet-700'], Unchanged: ['Aynı', 'bg-emerald-500/15 text-emerald-700'], Invalid: ['Geçersiz', 'bg-red-500/15 text-red-700'] };
const safeJson = (text, fallback) => { try { return JSON.parse(text); } catch { return fallback; } };

export default function DrivingMebbisImports() {
  const { toast } = useToast(); const { can } = useDrivingPermissions(); const canUpload = can(DRIVING.mebbisManage); const canApply = can(DRIVING.mebbisVerify);
  const [data, setData] = useState(null); const [detail, setDetail] = useState(null); const [file, setFile] = useState(null); const [type, setType] = useState('CandidateList'); const [groupId, setGroupId] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [excluded, setExcluded] = useState(() => new Set());
  const load = useCallback(async () => { setLoading(true); try { const value = await fetchDrivingMebbisImports(); setData(value); setGroupId((x) => x || value.groups?.find((g) => g.isActive)?.id || value.groups?.[0]?.id || ''); } catch (e) { toast({ title: 'Geri aktarımlar alınamadı', description: e.message, variant: 'destructive' }); } finally { setLoading(false); } }, [toast]);
  useEffect(() => { load(); }, [load]);
  const open = async (id) => { setSaving(true); try { setDetail(await fetchDrivingMebbisImport(id, { pageSize: 200 })); setExcluded(new Set()); } catch (e) { toast({ title: 'Önizleme alınamadı', description: e.message, variant: 'destructive' }); } finally { setSaving(false); } };
  const preview = async () => { if (!file || (type !== 'TermList' && !groupId)) return; const form = new FormData(); form.append('file', file); form.append('importType', type); if (groupId) form.append('studentGroupId', groupId); setSaving(true); try { const value = await previewDrivingMebbisImport(form); await load(); await open(value.id); toast({ title: 'Dosya işlendi; henüz hiçbir kayıt değiştirilmedi' }); } catch (e) { toast({ title: 'Önizleme oluşturulamadı', description: e.message, variant: 'destructive' }); } finally { setSaving(false); } };
  const apply = async () => { if (!detail) return; setSaving(true); try { await applyDrivingMebbisImport(detail.session.id, { expectedPreviewVersion: detail.session.previewVersion, excludedRowIds: [...excluded], createRetryFees: false }); toast({ title: 'Onaylanan değişiklikler uygulandı' }); await load(); await open(detail.session.id); } catch (e) { toast({ title: 'Geri aktarım uygulanamadı', description: e.message, variant: 'destructive' }); } finally { setSaving(false); } };
  const reject = async () => { const reason = window.prompt('Ret gerekçesi (en az 10 karakter):')?.trim() || ''; if (reason.length < 10) return; setSaving(true); try { await rejectDrivingMebbisImport(detail.session.id, { expectedPreviewVersion: detail.session.previewVersion, reason }); await load(); setDetail(null); } catch (e) { toast({ title: 'Önizleme reddedilemedi', description: e.message, variant: 'destructive' }); } finally { setSaving(false); } };
  const rows = detail?.rows || []; const applicable = useMemo(() => rows.filter((x) => ['Change', 'New'].includes(x.classification)), [rows]);
  if (loading && !data) return <DrivingLoading />;
  return <DrivingPage testId="driving-mebbis-imports-page">
    <DrivingPageHeader title="MEBBİS’ten Geri Aktarım" description="Excel/CSV dosyasını önce karantinada analiz edin; yalnız onaylanan değişiklikleri uygulayın." icon={FileInput} onRefresh={load} />
    <div className="grid gap-3 rounded-2xl border p-4 lg:grid-cols-[1fr_1fr_1fr_auto]">
      <label className="space-y-1 text-sm font-medium"><span>Dosya türü</span><select className="h-10 w-full rounded-md border bg-background px-3" value={type} onChange={(e) => setType(e.target.value)}>{Object.entries(TYPES).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label>
      <label className="space-y-1 text-sm font-medium"><span>Dönem {type === 'TermList' ? '(isteğe bağlı)' : ''}</span><select className="h-10 w-full rounded-md border bg-background px-3" value={groupId} onChange={(e) => setGroupId(e.target.value)}><option value="">Dönem seçin</option>{(data?.groups || []).map((g) => <option key={g.id} value={g.id}>{g.name}</option>)}</select></label>
      <label className="space-y-1 text-sm font-medium"><span>CSV veya XLSX · en fazla 5 MB</span><input className="block h-10 w-full rounded-md border p-1.5 text-sm" type="file" accept=".csv,.xlsx" onChange={(e) => setFile(e.target.files?.[0] || null)} /></label>
      <Button className="self-end" disabled={!canUpload || !file || saving || (type !== 'TermList' && !groupId)} onClick={preview}><Upload className="mr-2 h-4 w-4" />Önizleme oluştur</Button>
    </div>
    {detail && <section className="space-y-4 rounded-2xl border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">{TYPES[detail.session.importType]} · {detail.session.fileName}</h2><p className="text-xs text-muted-foreground">SHA-256: {detail.session.sha256} · önizleme v{detail.session.previewVersion}</p></div>{detail.session.status === 'PreviewReady' && <div className="flex gap-2"><Button variant="outline" disabled={saving} onClick={reject}><XCircle className="mr-2 h-4 w-4" />Reddet</Button><Button disabled={!canApply || saving || applicable.length === excluded.size} onClick={apply}><ShieldCheck className="mr-2 h-4 w-4" />Seçilenleri onayla ve uygula</Button></div>}</div>
      <div className="grid grid-cols-2 gap-2 md:grid-cols-6"><Mini label="Toplam" value={detail.session.totalRows} /><Mini label="Eşleşen" value={detail.session.matchedRows} /><Mini label="Bulunamayan" value={detail.session.notFoundRows} /><Mini label="Çelişki" value={detail.session.conflictRows} danger /><Mini label="Değişecek" value={detail.session.changeRows} /><Mini label="Yeni" value={detail.session.newRows} /></div>
      <div className="max-h-[520px] overflow-auto rounded-xl border"><table className="w-full min-w-[900px] text-left text-sm"><thead className="sticky top-0 bg-background"><tr><th className="p-3">Uygula</th><th>Satır</th><th>Sonuç</th><th>Eşleşme</th><th>Değişiklikler</th><th>Mesajlar</th></tr></thead><tbody>{rows.map((row) => { const state = CLASSES[row.classification] || [row.classification, '']; const changes = safeJson(row.changesJson, []); const messages = safeJson(row.messagesJson, []); const canSelect = ['Change', 'New'].includes(row.classification); return <tr key={row.id} className="border-t align-top"><td className="p-3"><input type="checkbox" disabled={!canSelect || detail.session.status !== 'PreviewReady'} checked={canSelect && !excluded.has(row.id)} onChange={() => setExcluded((old) => { const next = new Set(old); next.has(row.id) ? next.delete(row.id) : next.add(row.id); return next; })} /></td><td className="py-3">{row.rowNumber}</td><td className="py-3"><Badge className={`border-0 ${state[1]}`}>{state[0]}</Badge></td><td className="py-3 font-mono text-xs">{row.matchKey || '—'}</td><td className="py-3 text-xs">{changes.length ? changes.map((x) => <div key={x.field}><b>{x.field}:</b> {x.oldValue || '∅'} → {x.newValue}</div>) : '—'}</td><td className="py-3 text-xs text-red-700">{messages.join(' · ') || '—'}</td></tr>; })}</tbody></table></div>
    </section>}
    <div className="space-y-3"><h2 className="font-bold">Geçmiş geri aktarımlar</h2>{(data?.items || []).length === 0 ? <DrivingNotice icon={FileInput} title="Henüz geri aktarım yok" message="Bir CSV veya XLSX dosyasıyla önizleme oluşturun." /> : data.items.map((x) => <button type="button" key={x.id} onClick={() => open(x.id)} className="flex w-full items-center justify-between rounded-2xl border p-4 text-left hover:border-primary/40"><div><b>{TYPES[x.importType]}</b><p className="text-xs text-muted-foreground">{x.fileName} · {new Date(x.createdAtUtc).toLocaleString('tr-TR')} · {x.createdByName}</p></div><Badge variant="outline">{x.status}</Badge></button>)}</div>
  </DrivingPage>;
}
function Mini({ label, value, danger }) { return <div className={`rounded-xl border p-3 ${danger && value ? 'border-red-300 bg-red-500/5' : ''}`}><p className="text-xs text-muted-foreground">{label}</p><b className="text-xl">{value || 0}</b></div>; }
