import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CalendarPlus, CheckCircle2, ChevronLeft, ChevronRight, Download, Plus, Trash2 } from 'lucide-react';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { Badge } from '../../components/ui/badge';
import { useToast } from '../../hooks/use-toast';
import { downloadDrivingClassSchedule, downloadDrivingMebbisRoster, downloadDrivingTermReport, fetchDrivingTermWizardOptions, openDrivingTermWizard, validateDrivingTermWizard } from '../../lib/api/modules';
import { DrivingLoading, DrivingNotice, DrivingPage, DrivingPageHeader } from './_shared';

const STEPS = ['Dönem bilgileri', 'Kontenjan', 'Kursiyer listesi', 'Eksik bilgi ve evraklar', 'Teorik ders programı', 'Derslik ve öğretmen', 'MEBBİS’e hazır', 'Son kontrol ve çıktı'];
const localValue = (date) => new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16);
const iso = (value) => value ? new Date(value).toISOString() : null;
const initial = () => {
  const now = new Date(); const start = new Date(now.getTime() + 7 * 86400000); start.setHours(9, 0, 0, 0);
  const end = new Date(start.getTime() + 30 * 86400000); const deadline = new Date(start.getTime() - 86400000);
  return { name: `${now.getFullYear()} / ${now.getMonth() + 1}. Dönem`, description: '', termYear: now.getFullYear(), termNumber: now.getMonth() + 1, mebbisTermCode: '', quota: 24, registrationDeadlineUtc: localValue(deadline), licenseClass: 'B', studentProfileIds: [], theoryClassName: `${now.getFullYear()} B Sınıfı Teorik Eğitim`, instructorStaffId: '', room: '', theoryStartsAtUtc: localValue(start), theoryEndsAtUtc: localValue(end), sessions: [] };
};

export default function DrivingTermOpeningWizard() {
  const { toast } = useToast();
  const [step, setStep] = useState(0); const [form, setForm] = useState(initial);
  const [options, setOptions] = useState(null); const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false); const [validation, setValidation] = useState(null); const [result, setResult] = useState(null);
  useEffect(() => { fetchDrivingTermWizardOptions().then(setOptions).catch((e) => toast({ title: 'Sihirbaz açılamadı', description: e.message, variant: 'destructive' })).finally(() => setLoading(false)); }, [toast]);
  const students = options?.students || []; const instructors = options?.instructors || [];
  const selected = useMemo(() => students.filter((x) => form.studentProfileIds.includes(x.id)), [students, form.studentProfileIds]);
  const ready = selected.filter((x) => x.mebbisReady);
  const update = (key, value) => { setForm((x) => ({ ...x, [key]: value })); setValidation(null); };
  const payload = () => ({ ...form, quota: Number(form.quota), termYear: Number(form.termYear), termNumber: Number(form.termNumber), registrationDeadlineUtc: iso(form.registrationDeadlineUtc), theoryStartsAtUtc: iso(form.theoryStartsAtUtc), theoryEndsAtUtc: iso(form.theoryEndsAtUtc), sessions: form.sessions.map((x) => ({ ...x, startsAtUtc: iso(x.startsAtUtc), endsAtUtc: iso(x.endsAtUtc), instructorStaffId: x.instructorStaffId || null })) });
  const runValidation = async () => { setSaving(true); try { const value = await validateDrivingTermWizard(payload()); setValidation(value); return value; } catch (e) { toast({ title: 'Kontrol tamamlanamadı', description: e.message, variant: 'destructive' }); return null; } finally { setSaving(false); } };
  const next = async () => { if (step === 6) { const value = await runValidation(); if (value) setStep(7); } else setStep((x) => Math.min(7, x + 1)); };
  const open = async () => { setSaving(true); try { const value = await openDrivingTermWizard(payload()); setResult(value); toast({ title: 'Dönem güvenle açıldı' }); } catch (e) { toast({ title: 'Dönem açılamadı', description: e.message, variant: 'destructive' }); await runValidation(); } finally { setSaving(false); } };
  const download = async (kind) => { setSaving(true); try { const blob = kind === 'roster' ? await downloadDrivingMebbisRoster(result.groupId) : kind === 'report' ? await downloadDrivingTermReport(result.groupId) : await downloadDrivingClassSchedule(result.theoryClassId); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = kind === 'roster' ? 'mebbis-aday-listesi.csv' : kind === 'report' ? 'donem-raporu.pdf' : 'ders-programi.pdf'; anchor.click(); URL.revokeObjectURL(url); } catch (e) { toast({ title: 'Dosya indirilemedi', description: e.message, variant: 'destructive' }); } finally { setSaving(false); } };
  const toggleStudent = (id) => update('studentProfileIds', form.studentProfileIds.includes(id) ? form.studentProfileIds.filter((x) => x !== id) : [...form.studentProfileIds, id]);
  const addSession = () => { const start = form.theoryStartsAtUtc; const end = localValue(new Date(new Date(start).getTime() + 45 * 60000)); update('sessions', [...form.sessions, { subject: 'Trafik ve Çevre', topic: 'Temel trafik bilgisi', startsAtUtc: start, endsAtUtc: end, instructorStaffId: '', room: '' }]); };
  const changeSession = (index, key, value) => update('sessions', form.sessions.map((x, i) => i === index ? { ...x, [key]: value } : x));
  if (loading) return <DrivingLoading />;

  return <DrivingPage testId="driving-term-opening-wizard-page">
    <DrivingPageHeader title="Dönem Açma Sihirbazı" description="Dönemi, kursiyerleri ve teorik programı sekiz kontrollü adımda hazırlayın." icon={CalendarPlus} />
    <div className="overflow-x-auto rounded-2xl border p-3"><div className="flex min-w-[900px] gap-2">{STEPS.map((label, i) => <button key={label} type="button" onClick={() => !result && setStep(i)} className={`flex-1 rounded-xl px-2 py-3 text-left text-xs ${i === step ? 'bg-primary text-primary-foreground' : i < step ? 'bg-emerald-500/10 text-emerald-700' : 'bg-muted'}`}><span className="block font-bold">{i + 1}</span>{label}</button>)}</div></div>
    <section className="min-h-[380px] rounded-2xl border bg-card p-5">
      <h2 className="mb-5 text-lg font-semibold">{step + 1}. {STEPS[step]}</h2>
      {step === 0 && <div className="grid gap-4 md:grid-cols-2"><Field label="Dönem adı"><Input maxLength={120} value={form.name} onChange={(e) => update('name', e.target.value)} /></Field><Field label="MEBBİS dönem kodu"><Input maxLength={40} value={form.mebbisTermCode} onChange={(e) => update('mebbisTermCode', e.target.value)} /></Field><Field label="Dönem yılı"><Input type="number" min="2000" max="2100" value={form.termYear} onChange={(e) => update('termYear', e.target.value)} /></Field><Field label="Dönem numarası"><Input type="number" min="1" max="99" value={form.termNumber} onChange={(e) => update('termNumber', e.target.value)} /></Field><Field label="Son kayıt tarihi"><Input type="datetime-local" value={form.registrationDeadlineUtc} onChange={(e) => update('registrationDeadlineUtc', e.target.value)} /></Field><Field label="Açıklama"><Input maxLength={500} value={form.description} onChange={(e) => update('description', e.target.value)} /></Field></div>}
      {step === 1 && <div className="max-w-xl space-y-4"><Field label="Dönem kontenjanı"><Input type="number" min="1" max="100" value={form.quota} onChange={(e) => update('quota', e.target.value)} /></Field><div className="rounded-xl bg-muted p-4 text-sm">Seçilen: <b>{selected.length}</b> · Kalan: <b>{Math.max(0, Number(form.quota) - selected.length)}</b> · Tek teorik sınıf üst sınırı: 100</div></div>}
      {step === 2 && <div className="space-y-2"><p className="text-sm text-muted-foreground">Yalnızca açık durumda ve başka döneme atanmamış kursiyerler listelenir.</p><div className="max-h-[430px] overflow-auto rounded-xl border">{students.map((x) => <label key={x.id} className="flex cursor-pointer items-start gap-3 border-b p-3 last:border-0"><input type="checkbox" className="mt-1" checked={form.studentProfileIds.includes(x.id)} disabled={!form.studentProfileIds.includes(x.id) && selected.length >= Number(form.quota)} onChange={() => toggleStudent(x.id)} /><div className="flex-1"><b>{x.fullName}</b><p className="text-xs text-muted-foreground">#{x.studentNumber} · {x.licenseClass} · {x.status}</p></div><Badge variant={x.mebbisReady ? 'default' : 'outline'}>{x.mebbisReady ? 'Hazır' : `${x.missing.length} eksik`}</Badge></label>)}</div></div>}
      {step === 3 && <div className="space-y-3">{selected.length === 0 ? <DrivingNotice icon={AlertTriangle} title="Kursiyer seçilmedi" message="Önce kursiyer listesinden seçim yapın." /> : selected.map((x) => <div key={x.id} className="rounded-xl border p-3"><div className="flex justify-between"><b>{x.fullName}</b><Badge className={x.mebbisReady ? 'bg-emerald-600' : 'bg-red-600'}>{x.mebbisReady ? 'Eksiksiz' : `${x.missing.length} eksik`}</Badge></div>{x.missing.length > 0 && <div className="mt-2 flex flex-wrap gap-1">{x.missing.map((m) => <Badge key={m} variant="outline" className="border-red-300 text-red-700">{m}</Badge>)}</div>}</div>)}</div>}
      {step === 4 && <div className="space-y-3"><div className="flex justify-end"><Button type="button" variant="outline" onClick={addSession}><Plus className="mr-2 h-4 w-4" />Ders ekle</Button></div>{form.sessions.map((x, i) => <div key={i} className="grid gap-3 rounded-xl border p-3 lg:grid-cols-6"><Input maxLength={120} placeholder="Ders" value={x.subject} onChange={(e) => changeSession(i, 'subject', e.target.value)} /><Input maxLength={250} placeholder="Konu" value={x.topic} onChange={(e) => changeSession(i, 'topic', e.target.value)} /><Input type="datetime-local" value={x.startsAtUtc} onChange={(e) => changeSession(i, 'startsAtUtc', e.target.value)} /><Input type="datetime-local" value={x.endsAtUtc} onChange={(e) => changeSession(i, 'endsAtUtc', e.target.value)} /><select className="rounded-md border bg-background px-2 text-sm" value={x.instructorStaffId} onChange={(e) => changeSession(i, 'instructorStaffId', e.target.value)}><option value="">Ana öğretmen</option>{instructors.map((t) => <option key={t.id} value={t.id}>{t.fullName}</option>)}</select><Button variant="ghost" onClick={() => update('sessions', form.sessions.filter((_, n) => n !== i))}><Trash2 className="h-4 w-4 text-red-600" /></Button></div>)}{form.sessions.length === 0 && <DrivingNotice icon={CalendarPlus} title="Program boş" message="En az bir teorik ders ekleyin." />}</div>}
      {step === 5 && <div className="grid gap-4 md:grid-cols-2"><Field label="Teorik sınıf adı"><Input maxLength={150} value={form.theoryClassName} onChange={(e) => update('theoryClassName', e.target.value)} /></Field><Field label="Ehliyet sınıfı"><Input maxLength={20} value={form.licenseClass} onChange={(e) => update('licenseClass', e.target.value.toUpperCase())} /></Field><Field label="Ana öğretmen"><select className="h-10 w-full rounded-md border bg-background px-3" value={form.instructorStaffId} onChange={(e) => update('instructorStaffId', e.target.value)}><option value="">Seçin</option>{instructors.map((x) => <option key={x.id} value={x.id}>{x.fullName}</option>)}</select></Field><Field label="Derslik"><Input maxLength={120} value={form.room} onChange={(e) => update('room', e.target.value)} /></Field><Field label="Eğitim başlangıcı"><Input type="datetime-local" value={form.theoryStartsAtUtc} onChange={(e) => update('theoryStartsAtUtc', e.target.value)} /></Field><Field label="Eğitim bitişi"><Input type="datetime-local" value={form.theoryEndsAtUtc} onChange={(e) => update('theoryEndsAtUtc', e.target.value)} /></Field></div>}
      {step === 6 && <div className="grid gap-4 md:grid-cols-3"><Summary label="Seçilen kursiyer" value={selected.length} /><Summary label="MEBBİS’e hazır" value={ready.length} good={ready.length === selected.length && selected.length > 0} /><Summary label="Düzeltme gereken" value={selected.length - ready.length} good={selected.length === ready.length} /><div className="md:col-span-3 rounded-xl bg-muted p-4 text-sm">Sonraki adımda sunucu tüm veriyi ve zaman çakışmalarını yeniden kontrol eder.</div></div>}
      {step === 7 && <div className="space-y-4">{!validation && !result && <Button disabled={saving} onClick={runValidation}>Son kontrolü çalıştır</Button>}{validation && <><div className={`rounded-xl p-4 ${validation.ready ? 'bg-emerald-500/10 text-emerald-800' : 'bg-red-500/10 text-red-800'}`}><b>{validation.ready ? 'Dönem açılmaya hazır.' : 'Düzeltilmesi gereken alanlar var.'}</b><p className="mt-1 text-sm">{validation.selectedCount} kursiyer · {validation.mebbisReadyCount} MEBBİS’e hazır · {validation.sessionCount} ders</p></div>{validation.errors?.map((x) => <p key={x} className="rounded-lg border border-red-300 p-2 text-sm text-red-700">{x}</p>)}{validation.warnings?.map((x) => <p key={x} className="rounded-lg border border-amber-300 p-2 text-sm text-amber-700">{x}</p>)}{validation.ready && !result && <Button disabled={saving} onClick={open}><CheckCircle2 className="mr-2 h-4 w-4" />Dönemi aç ve atamaları tamamla</Button>}</>}{result && <div className="space-y-4"><DrivingNotice icon={CheckCircle2} title={`${result.name} açıldı`} message={`${result.studentCount} kursiyer ve ${result.sessionCount} ders başarıyla oluşturuldu.`} /><div className="flex flex-wrap gap-2"><OutputButton onClick={() => download('roster')} label="MEBBİS aday listesi" /><OutputButton onClick={() => download('report')} label="Dönem raporu" /><OutputButton onClick={() => download('schedule')} label="Ders programı" /></div></div>}</div>}
    </section>
    {!result && <div className="flex justify-between"><Button variant="outline" disabled={step === 0 || saving} onClick={() => setStep((x) => x - 1)}><ChevronLeft className="mr-2 h-4 w-4" />Geri</Button>{step < 7 && <Button disabled={saving} onClick={next}>Devam<ChevronRight className="ml-2 h-4 w-4" /></Button>}</div>}
  </DrivingPage>;
}

function Field({ label, children }) { return <label className="space-y-1.5 text-sm"><span className="font-medium">{label}</span>{children}</label>; }
function Summary({ label, value, good }) { return <div className={`rounded-xl border p-4 ${good ? 'border-emerald-400 bg-emerald-500/5' : ''}`}><p className="text-sm text-muted-foreground">{label}</p><b className="text-2xl">{value}</b></div>; }
function OutputButton({ onClick, label }) { return <Button variant="outline" onClick={onClick}><Download className="mr-2 h-4 w-4" />{label}</Button>; }
