import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, BookOpenCheck, CheckCircle2, Plus, RefreshCw, Search } from 'lucide-react';
import { Badge } from '../../components/ui/badge';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { useToast } from '../../hooks/use-toast';
import { createDrivingMebbisError, fetchDrivingMebbisError, fetchDrivingMebbisErrors, reportDrivingMebbisError, resolveDrivingMebbisError, syncDrivingMebbisErrorDefaults } from '../../lib/api/modules';
import { DRIVING, useDrivingPermissions } from '../../lib/drivingPermissions';
import { DrivingLoading, DrivingNotice, DrivingPage, DrivingPageHeader, DrivingStatCard } from './_shared';

const severity = { Blocking: ['Engelleyici', 'bg-red-500/15 text-red-700'], Warning: ['Kontrol gerekli', 'bg-amber-500/15 text-amber-700'], Information: ['Bilgi', 'bg-sky-500/15 text-sky-700'] };

export default function DrivingMebbisErrorLibrary() {
  const { toast } = useToast(); const { can } = useDrivingPermissions(); const canManage = can(DRIVING.mebbisManage);
  const [data, setData] = useState(null); const [detail, setDetail] = useState(null); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { setData(await fetchDrivingMebbisErrors({ search: search || undefined })); } catch (e) { toast({ title: 'Hata kütüphanesi alınamadı', description: e.message, variant: 'destructive' }); } finally { setLoading(false); } }, [search, toast]);
  useEffect(() => { const timer = setTimeout(load, search ? 300 : 0); return () => clearTimeout(timer); }, [load, search]);
  const open = async (id) => { try { setDetail(await fetchDrivingMebbisError(id)); } catch (e) { toast({ title: 'Hata ayrıntısı alınamadı', description: e.message, variant: 'destructive' }); } };
  const sync = async () => { try { const r = await syncDrivingMebbisErrorDefaults(); toast({ title: `${r.created || 0} varsayılan kart eklendi` }); await load(); } catch (e) { toast({ title: 'Rehber kurulamadı', description: e.message, variant: 'destructive' }); } };
  const create = async () => { const title = prompt('Yeni hata başlığı:')?.trim(); if (!title) return; const description = prompt('Açıklama (en az 10 karakter):')?.trim(); const cause = prompt('Olası neden:')?.trim(); const steps = prompt('Çözüm adımları (her satıra bir adım):')?.split('\n').map(x => x.trim()).filter(Boolean); if (!description || !cause || !steps?.length) return; try { await createDrivingMebbisError({ code: title, title, description, possibleCause: cause, resolutionSteps: steps, severity: 'Warning', isActive: true, expectedVersion: 0 }); await load(); } catch (e) { toast({ title: 'Kart oluşturulamadı', description: e.message, variant: 'destructive' }); } };
  const report = async (id) => { const note = prompt('Hata olayı notu (kişisel veri yazmayın):')?.trim(); if (!note) return; try { await reportDrivingMebbisError(id, { note, sourceType: 'Manual' }); await open(id); await load(); } catch (e) { toast({ title: 'Hata kaydedilemedi', description: e.message, variant: 'destructive' }); } };
  const resolve = async (x) => { const resolutionNote = prompt('Uygulanan çözüm:')?.trim(); if (!resolutionNote) return; try { await resolveDrivingMebbisError(x.id, { resolutionNote, expectedVersion: x.version }); await open(detail.definition.id); await load(); } catch (e) { toast({ title: 'Çözüm kaydedilemedi', description: e.message, variant: 'destructive' }); } };
  if (loading && !data) return <DrivingLoading />; const items = data?.items || []; const summary = data?.summary || {};
  return <DrivingPage testId="driving-mebbis-error-library-page">
    <DrivingPageHeader title="MEBBİS Hata Kütüphanesi" description="Yaygın hataları, nedenlerini ve kurumunuzun doğrulanmış çözüm adımlarını tek yerde yönetin." icon={BookOpenCheck} onRefresh={load} />
    <div className="flex flex-wrap justify-end gap-2">{canManage && <><Button variant="outline" onClick={sync}><RefreshCw className="mr-2 h-4 w-4" />Varsayılan rehberi kur</Button><Button onClick={create}><Plus className="mr-2 h-4 w-4" />Yeni hata kartı</Button></>}</div>
    <div className="grid grid-cols-3 gap-3"><DrivingStatCard label="Hata kartı" value={summary.total || 0} icon={BookOpenCheck} tone="brand" /><DrivingStatCard label="Toplam görülme" value={summary.occurrences || 0} icon={AlertTriangle} tone="amber" /><DrivingStatCard label="Çözüm bekleyen" value={summary.unresolved || 0} icon={CheckCircle2} tone="violet" /></div>
    <div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" maxLength={100} placeholder="Kod, hata, neden veya açıklama ara…" value={search} onChange={e => setSearch(e.target.value)} /></div>
    {!items.length ? <DrivingNotice icon={BookOpenCheck} title="Henüz hata kartı yok" message="Yetkili personel varsayılan MEBBİS rehberini tek tıkla kurabilir." /> : <div className="grid gap-3 lg:grid-cols-2">{items.map(x => { const tone = severity[x.severity] || [x.severity, '']; return <button key={x.id} onClick={() => open(x.id)} className="rounded-2xl border p-4 text-left hover:bg-muted/40"><div className="flex items-start justify-between gap-2"><b>{x.title}</b><Badge className={tone[1]}>{tone[0]}</Badge></div><p className="mt-2 text-sm text-muted-foreground">{x.description}</p><div className="mt-3 flex gap-2"><Badge variant="outline">{x.occurrenceCount} kez</Badge>{x.unresolvedCount > 0 && <Badge className="bg-red-500/15 text-red-700">{x.unresolvedCount} açık</Badge>}<span className="ml-auto text-xs text-muted-foreground">{x.code}</span></div></button>; })}</div>}
    {detail && <div className="fixed inset-0 z-50 flex justify-end bg-black/40" onClick={() => setDetail(null)}><div className="h-full w-full max-w-2xl overflow-y-auto bg-background p-6 shadow-xl" onClick={e => e.stopPropagation()}><div className="flex justify-between"><h2 className="text-xl font-bold">{detail.definition.title}</h2><Button variant="ghost" onClick={() => setDetail(null)}>Kapat</Button></div><h3 className="mt-6 font-semibold">Olası neden</h3><p className="text-sm text-muted-foreground">{detail.definition.possibleCause}</p><h3 className="mt-5 font-semibold">Çözüm adımları</h3><ol className="mt-2 list-decimal space-y-2 pl-5 text-sm">{detail.definition.resolutionSteps.map(x => <li key={x}>{x}</li>)}</ol>{canManage && <Button className="mt-5" onClick={() => report(detail.definition.id)}>Bu hatayı kaydet</Button>}<h3 className="mt-6 font-semibold">İlgili kayıtlar ({detail.total})</h3><div className="mt-2 space-y-2">{detail.occurrences.map(x => <div key={x.id} className="rounded-xl border p-3"><div className="flex justify-between gap-2"><b className="text-sm">{x.studentName || 'Genel işlem'}{x.studentNumber ? ` • #${x.studentNumber}` : ''}</b><Badge variant="outline">{x.resolvedAtUtc ? 'Çözüldü' : 'Açık'}</Badge></div><p className="mt-1 text-sm">{x.note}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(x.occurredAtUtc).toLocaleString('tr-TR')} • {x.reportedByName}</p>{x.resolutionNote && <p className="mt-2 rounded-lg bg-emerald-500/10 p-2 text-sm">Çözüm: {x.resolutionNote}</p>}{canManage && !x.resolvedAtUtc && <Button className="mt-2" size="sm" variant="outline" onClick={() => resolve(x)}>Çözüldü olarak işaretle</Button>}</div>)}</div></div></div>}
  </DrivingPage>;
}
