import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, FileSpreadsheet, RefreshCw, ShieldCheck, Upload } from 'lucide-react';
import { Badge } from '../../components/ui/badge';
import { Button } from '../../components/ui/button';
import { useToast } from '../../hooks/use-toast';
import { applyDrivingMebbisImport, fetchDrivingMebbisExamResult, fetchDrivingMebbisExamResults, previewDrivingMebbisImport } from '../../lib/api/modules';
import { DRIVING, useDrivingPermissions } from '../../lib/drivingPermissions';
import { DrivingLoading, DrivingNotice, DrivingPage, DrivingPageHeader } from './_shared';

const STATUS = { Change: ['Uygulanabilir', 'bg-blue-500/15 text-blue-700'], Unchanged: ['Aynı', 'bg-emerald-500/15 text-emerald-700'], Conflict: ['Çelişki', 'bg-red-500/15 text-red-700'], NotFound: ['Bulunamadı', 'bg-slate-500/15 text-slate-700'], Invalid: ['Geçersiz', 'bg-red-500/15 text-red-700'] };

export default function DrivingMebbisExamResults() {
  const { toast } = useToast(); const { can } = useDrivingPermissions();
  const [data, setData] = useState(null); const [detail, setDetail] = useState(null); const [groupId, setGroupId] = useState(''); const [file, setFile] = useState(null); const [excluded, setExcluded] = useState(() => new Set()); const [createFees, setCreateFees] = useState(true); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const value = await fetchDrivingMebbisExamResults(); setData(value); setGroupId((old) => old || value.groups?.find((x) => x.isActive)?.id || value.groups?.[0]?.id || ''); } catch (e) { toast({ title: 'Sınav mutabakatları alınamadı', description: e.message, variant: 'destructive' }); } finally { setLoading(false); } }, [toast]);
  useEffect(() => { load(); }, [load]);
  const open = async (id) => { setSaving(true); try { setDetail(await fetchDrivingMebbisExamResult(id, { pageSize: 500 })); setExcluded(new Set()); } catch (e) { toast({ title: 'Önizleme açılamadı', description: e.message, variant: 'destructive' }); } finally { setSaving(false); } };
  const preview = async () => { if (!file || !groupId) return; const form = new FormData(); form.append('file', file); form.append('importType', 'ExamResults'); form.append('studentGroupId', groupId); setSaving(true); try { const result = await previewDrivingMebbisImport(form); await load(); await open(result.id); toast({ title: 'Sınav sonucu önizlemesi hazır', description: 'Henüz hiçbir sonuç veya finans kaydı değiştirilmedi.' }); } catch (e) { toast({ title: 'Dosya analiz edilemedi', description: e.message, variant: 'destructive' }); } finally { setSaving(false); } };
  const apply = async () => { const session = detail?.session; if (!session) return; setSaving(true); try { const result = await applyDrivingMebbisImport(session.id, { expectedPreviewVersion: session.previewVersion, excludedRowIds: [...excluded], createRetryFees: createFees }); toast({ title: `${result.applied} sonuç uygulandı`, description: `${result.retryRequired || 0} tekrar gerekli, ${result.retryFeesCreated || 0} ücret oluşturuldu.` }); await load(); await open(session.id); } catch (e) { toast({ title: 'Sonuçlar uygulanamadı', description: e.message, variant: 'destructive' }); } finally { setSaving(false); } };
  const rows = detail?.rows || []; const actionable = useMemo(() => rows.filter((x) => x.classification === 'Change'), [rows]);
  if (loading && !data) return <DrivingLoading />;
  const summary = detail?.summary || {}; const session = detail?.session;
  return <DrivingPage testId="driving-mebbis-exam-results-page">
    <DrivingPageHeader title="Sınav Sonucu Mutabakatı" description="MEBBİS sonuç dosyasını sınav hakkı, puan, tekrar ve finans etkisiyle birlikte güvenli önizleyin." icon={FileSpreadsheet} onRefresh={load} />
    <div className="grid gap-3 rounded-2xl border p-4 lg:grid-cols-[1fr_1.4fr_auto]">
      <label className="space-y-1 text-sm font-medium"><span>Dönem</span><select className="h-10 w-full rounded-md border bg-background px-3" value={groupId} onChange={(e) => setGroupId(e.target.value)}><option value="">Dönem seçin</option>{(data?.groups || []).map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
      <label className="space-y-1 text-sm font-medium"><span>MEBBİS CSV/XLSX · en fazla 5 MB</span><input type="file" accept=".csv,.xlsx" className="block h-10 w-full rounded-md border p-1.5 text-sm" onChange={(e) => setFile(e.target.files?.[0] || null)} /></label>
      <Button className="self-end" disabled={!can(DRIVING.mebbisManage) || !file || !groupId || saving} onClick={preview}><Upload className="mr-2 h-4 w-4" />Güvenli önizleme</Button>
    </div>
    {session && <section className="space-y-4 rounded-2xl border p-4">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-bold">{session.fileName}</h2><p className="text-xs text-muted-foreground">{session.status} · önizleme v{session.previewVersion} · {new Date(session.createdAtUtc).toLocaleString('tr-TR')}</p></div>{session.status === 'PreviewReady' && <Button disabled={!can(DRIVING.mebbisVerify) || saving || actionable.length === excluded.size} onClick={apply}><ShieldCheck className="mr-2 h-4 w-4" />Seçilen sonuçları uygula</Button>}</div>
      <div className="grid grid-cols-2 gap-2 md:grid-cols-6"><Mini label="Toplam" value={summary.total} /><Mini label="Geçti" value={summary.passed} ok /><Mini label="Kaldı" value={summary.failed} danger /><Mini label="Puan farkı" value={summary.scoreMismatch} danger /><Mini label="Tekrar gerekli" value={summary.retryRequired} /><Mini label="Hakkı doldu" value={summary.outOfAttempts} danger /></div>
      <div className="grid gap-3 rounded-xl border border-amber-300/60 bg-amber-500/5 p-3 md:grid-cols-[1fr_auto]"><div><b>Finans ve zorunlu eğitim etkisi</b><p className="text-sm">{summary.feeCandidates || 0} kursiyer · toplam {Number(summary.feeTotal || 0).toLocaleString('tr-TR', { style: 'currency', currency: 'TRY' })} · {summary.mandatoryExtraLesson || 0} zorunlu ek ders{summary.contractMissing ? ` · ${summary.contractMissing} sözleşme eksik` : ''}</p></div><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={createFees} onChange={(e) => setCreateFees(e.target.checked)} />Tekrar sınav ücretlerini oluştur</label></div>
      {summary.contractMissing > 0 && <DrivingNotice icon={AlertTriangle} title="Sözleşmesi eksik kursiyer var" message="Sonuç uygulanır ancak sözleşme bulunmayan kursiyer için finans borcu oluşturulmaz." />}
      <div className="max-h-[620px] overflow-auto rounded-xl border"><table className="w-full min-w-[1150px] text-left text-sm"><thead className="sticky top-0 bg-background"><tr><th className="p-3">Uygula</th><th>Kursiyer</th><th>Sınav hakkı</th><th>Önceki</th><th>MEBBİS</th><th>Tekrar/ücret</th><th>Durum</th></tr></thead><tbody>{rows.map((row) => { const state = STATUS[row.classification] || [row.classification, '']; const selectable = row.classification === 'Change'; return <tr key={row.rowId} className="border-t align-top"><td className="p-3"><input type="checkbox" disabled={!selectable || session.status !== 'PreviewReady'} checked={selectable && !excluded.has(row.rowId)} onChange={() => setExcluded((old) => { const next = new Set(old); next.has(row.rowId) ? next.delete(row.rowId) : next.add(row.rowId); return next; })} /></td><td className="py-3 pr-3"><b>{row.name || 'Adsız kayıt'}</b><div className="font-mono text-xs text-muted-foreground">{row.maskedIdentity}</div></td><td className="py-3 pr-3">{row.examTitle || '—'}<div className="text-xs">{row.examType || ''} · {row.attemptNo || 0}. hak · {row.remainingAttempts || 0} kalan</div></td><td className="py-3 pr-3">{row.previousResult || '—'}<div className="text-xs">Puan: {row.previousScore ?? '—'}</div></td><td className="py-3 pr-3"><b>{row.incomingPassed === true ? 'Geçti' : row.incomingPassed === false ? 'Kaldı' : 'Belirsiz'}</b><div className={`text-xs ${row.scoreMismatch ? 'text-red-600 font-bold' : ''}`}>Puan: {row.importedScore ?? '—'}</div></td><td className="py-3 pr-3">{row.outOfAttempts ? <Badge variant="destructive">Hak doldu</Badge> : row.retryRequired ? <><Badge variant="outline">Tekrar gerekli</Badge><div className="mt-1 text-xs">{row.feeWillBeCreated ? `${Number(row.feeAmount).toLocaleString('tr-TR')} ₺ tekrar ücreti` : row.contractMissing ? 'Sözleşme eksik' : 'Tekrar ücretsiz'}</div></> : <CheckCircle2 className="h-4 w-4 text-emerald-600" />}{row.extraLessonMinutes > 0 && <div className="mt-1 text-xs text-amber-700">{row.extraLessonMinutes} dk zorunlu ek ders · {Number(row.extraLessonFee || 0).toLocaleString('tr-TR')} ₺</div>}</td><td className="py-3 pr-3"><Badge className={`border-0 ${state[1]}`}>{state[0]}</Badge><div className="mt-1 max-w-[220px] text-xs text-muted-foreground">{row.message}</div></td></tr>; })}</tbody></table></div>
    </section>}
    <div className="space-y-3"><h2 className="font-bold">Sınav sonucu aktarım geçmişi</h2>{(data?.imports || []).length === 0 ? <DrivingNotice icon={FileSpreadsheet} title="Henüz sınav sonuç dosyası yok" message="MEBBİS CSV veya XLSX dosyasıyla güvenli önizleme oluşturun." /> : data.imports.map((x) => <button type="button" key={x.id} onClick={() => open(x.id)} className="flex w-full items-center justify-between rounded-2xl border p-4 text-left hover:border-primary/40"><div><b>{x.fileName}</b><p className="text-xs text-muted-foreground">{x.totalRows} satır · {new Date(x.createdAtUtc).toLocaleString('tr-TR')} · {x.createdByName}</p></div><Badge variant="outline">{x.status}</Badge></button>)}</div>
  </DrivingPage>;
}
function Mini({ label, value, danger, ok }) { return <div className={`rounded-xl border p-3 ${danger && value ? 'border-red-300 bg-red-500/5' : ok && value ? 'border-emerald-300 bg-emerald-500/5' : ''}`}><p className="text-xs text-muted-foreground">{label}</p><b className="text-xl">{value || 0}</b></div>; }
