import type { RoleId } from "./site-experience-data"

export type CapabilityGroup = { title: string; summary: string; items: readonly (readonly [string, string])[] }
export type RoleCapabilities = { scope: string; groups: readonly CapabilityGroup[] }

// Audited against desktop ModernSidebar, App routes, navigation hubs and the
// mobile role router. These describe available screens, never grant access.
const finance: CapabilityGroup[] = [
  { title: "Hesaplar ve tahsilat", summary: "Öğrencinin ödeme planından günlük kasa hareketine.", items: [
    ["Muhasebe özeti", "Tahsilat, gider, net akış, gecikme ve bekleyen ödemeleri birlikte izleyin."],
    ["Cari hesaplar", "Öğrenciye ait borç, ödeme planı ve hesap hareketlerini inceleyin."],
    ["Tahsilatlar", "Ödemeleri kaydedin; öğrenci, tarih ve ödeme durumuna göre takip edin."],
    ["Taksitler", "Taksit planlarını, vadeleri, ödenen ve kalan tutarları yönetin."],
    ["Tahsilat takvimi", "Vadesi gelen ödemeleri takvim üzerinden izleyin."],
    ["Geciken ödemeler", "Vadesi geçen kayıtları ve geciken toplam tutarı görün."],
    ["Gecikme kuralları", "Kurumun gecikme ve hatırlatma kurallarını düzenleyin."],
    ["Toplu işlemler", "Yetkiniz dahilindeki finans kayıtlarında toplu işlemler yapın."],
  ] },
  { title: "Belgeler, gider ve bordro", summary: "Finansal kayıtların bütün tamamlayıcı işlemleri.", items: [
    ["Fatura ve makbuz", "Ödeme belgelerini oluşturun ve kayıtlı belgeleri inceleyin."],
    ["İadeler", "İade işlemlerini ve ilgili hesap hareketlerini takip edin."],
    ["İndirim ve burs", "Öğrenci hesaplarına tanımlanan indirim ve bursları yönetin."],
    ["Giderler", "Kurumun gider kayıtlarını ve gider dağılımını takip edin."],
    ["Maaş yönetimi", "Personel maaşlarını ve bordro ile ilgili kayıtları yönetin."],
  ] },
  { title: "Raporlama ve denetim", summary: "Her hareketin izini koruyun.", items: [
    ["Kasa raporu", "Döneme göre gelir, gider ve kasa durumunu inceleyin."],
    ["Hesap defteri", "Finansal hareketleri tarih ve hesap bazında listeleyin."],
    ["Mutabakat", "Finans kayıtlarını karşılaştırın ve mutabakat durumunu takip edin."],
    ["Dışa aktarım", "Yetkili olduğunuz finans verilerini raporlama için dışa aktarın."],
    ["Denetim kaydı", "Finansal işlemlerin kayıt geçmişini inceleyin."],
  ] },
]
const communication: CapabilityGroup = { title: "İletişim ve kişisel alan", summary: "İş akışını tamamlayan günlük araçlar.", items: [
  ["Mesajlar", "Yetkili olduğunuz kişilerle kurum içi yazışmaları takip edin."],
  ["Duyurular ve bildirimler", "Size veya sorumlu olduğunuz gruplara gönderilen duyuruları görün."],
  ["Profil ve ayarlar", "Kişisel bilgilerinizi ve hesabınızın kullanılabilir tercihlerini düzenleyin."],
] }
const admin: CapabilityGroup[] = [
  { title: "Kurum ve organizasyon", summary: "Büyük resimden tek bir şubenin detayına.", items: [
    ["Yönetim panosu ve kurum özeti", "Günlük göstergeleri, akademik durumu ve kurumun genel akışını izleyin."],
    ["Operasyon", "Günlük kurum işlerini ve operasyonel kayıtları takip edin."],
    ["Şube kaydı", "Kurumun şubelerini ve şube bilgilerini yönetin."],
    ["Şube karşılaştırma", "Yetkili olduğunuz şubelerin göstergelerini karşılaştırın."],
    ["Organizasyon birimleri", "Kurumun birimlerini ve kullanıcıların kapsamlarını düzenleyin."],
    ["İdari birimler", "İdari ekipleri ve birim yapılanmasını takip edin."],
    ["Kurum içi arama", "İzin verilen öğrenci, personel ve kurum kayıtlarına aramayla ulaşın."],
    ["Kurum profili ve ayarlar", "Kurum bilgilerini ve erişiminize açık sistem tercihlerini düzenleyin."],
  ] },
  { title: "Kişiler ve kayıt", summary: "Öğrenci, veli ve ekip bilgileri aynı bütünlükte.", items: [
    ["Öğrenciler ve öğrenci kaydı", "Öğrenci kayıtlarını oluşturun, inceleyin ve güncelleyin."],
    ["Veliler", "Veli kayıtlarını ve öğrenci bağlantılarını yönetin."],
    ["Öğretmenler", "Öğretmen kayıtlarını ve atamalarını takip edin."],
    ["Personel dizini ve personel kaydı", "Kurum ekibinin kayıtlarını ve görev bilgilerini yönetin."],
    ["Muhasebe kaydı", "Muhasebe ekibine ait kullanıcı kayıtlarını oluşturun."],
    ["Personel / İK", "Personel, izin ve insan kaynakları süreçlerini takip edin."],
    ["Pasif kayıtlar", "Aktif kullanım dışına alınan kayıtları inceleyin."],
    ["Sözleşme ve formlar", "Kurumun form ve sözleşme işlemlerini yönetin."],
  ] },
  { title: "Akademik yönetim", summary: "Program, devam, içerik ve ölçme değerlendirme.", items: [
    ["Akademik yönetim", "Ders ve eğitim süreçlerinin genel durumunu takip edin."],
    ["Sınıflar ve gruplar", "Sınıf, grup ve ilgili öğrenci yapılanmasını düzenleyin."],
    ["Ders programı", "Kurumun ders takvimini ve ders planlamasını yönetin."],
    ["Öğretmen programı", "Öğretmenlerin haftalık ders dağılımını inceleyin."],
    ["Devamsızlık", "Yoklama ve devam kayıtlarını, mazeretleri ve raporları takip edin."],
    ["Kurs yönetimi", "Kurs kayıtlarını ve kursun ilgili eğitim bilgilerini yönetin."],
    ["İçerikler", "Kurumun ders materyallerini ve içeriklerini yönetin."],
    ["Sorular", "Kurum soru kayıtlarını ve soru bankasını inceleyin."],
    ["Sınavlar", "Sınav süreçlerini ve sonuç kayıtlarını takip edin."],
    ["Sınav kağıtları", "Sınav kağıdı hazırlama ve ilgili belge işlemlerini yürütün."],
    ["Kütüphane", "Kütüphane kaynaklarını ve ödünç kayıtlarını takip edin."],
    ["Raporlar", "Yetkiniz kapsamındaki akademik ve kurum raporlarını inceleyin."],
  ] },
  { title: "Görevler ve kurum hizmetleri", summary: "Ekip çalışmasının günlük ayrıntıları.", items: [
    ["Görev merkezi", "Görevleri oluşturun, atayın ve ilerlemelerini takip edin."],
    ["Nöbet oluşturma ve tüm nöbetler", "Nöbet planlarını ve görevlendirmeleri yönetin."],
    ["Görüşme akışı", "Görüşme taleplerini ve planlanan görüşmeleri takip edin."],
    ["Servis takip", "Servis, rota, öğrenci ve sefer kayıtlarını yetkiniz kapsamında izleyin."],
    ["Yemekhane", "Haftalık yemek programına ve yetkili olduğunuz menü işlemlerine ulaşın."],
  ] },
  ...finance,
  { title: "Yetki, onay ve arşiv", summary: "Kurumun kontrol noktalarını yönetin.", items: [
    ["Finans kontrolü ve finans onayları", "Finansal durumu ve onay bekleyen finans işlemlerini değerlendirin."],
    ["Personel onayları", "Personelle ilgili onay bekleyen işlemleri değerlendirin."],
    ["Rol yönetimi", "Kullanıcı rollerini, ek rolleri ve özel rol tanımlarını yönetin."],
    ["Yetki matrisi", "Kullanıcıların işlem izinlerini ve veri erişim kapsamlarını düzenleyin."],
    ["Şifre talepleri", "Kullanıcıların şifre sıfırlama taleplerini takip edin."],
    ["İdari kayıtlar", "Kurumun idari işlem kayıtlarını yönetin."],
    ["Belge merkezi", "Yetkili olduğunuz belgeleri yükleyin ve düzenleyin."],
    ["Kayıt geçmişi", "İdari işlemlerin denetim geçmişini inceleyin."],
    ["Verilerimi indir", "Yönetici yetkisiyle kurum verisinin indirme işlemini yürütün."],
    ["Duyuru ve bildirim yönetimi", "Kurumun duyurularını ve bildirimlerini ilgili alıcılara iletin."],
    ["Destek", "Kurumunuzun destek kayıtlarını oluşturun ve durumunu takip edin."],
  ] }, communication,
]
export const roleCapabilities: Record<RoleId, RoleCapabilities> = {
  yonetici: { scope: "Kurum yöneticisi yalnızca yetkili olduğu kurum ve kapsam içindeki kayıtları yönetir. Özelliklerin kullanılabilirliği kurumun açtığı modüllere ve tanımlanan izinlere bağlıdır.", groups: admin },
  ogretmen: { scope: "Öğretmen kendi derslerine, sınıflarına ve yetkilendirildiği öğrencilere erişir. Rehberlik branşı ayrı rehberlik deneyimini kullanır.", groups: [
    { title: "Ders ve öğrenci takibi", summary: "Hazırlıktan dersin sonuna kadar.", items: [
      ["Öğretmen panosu", "Günün derslerini, öğrenci durumunu ve size ait iş akışını görün."],
      ["Ders programı", "Haftalık derslerinizi, saatlerini ve sınıflarını takip edin."],
      ["Öğrencilerim", "Sorumlu olduğunuz öğrencilerin bilgilerini ve gelişimini inceleyin."],
      ["Yoklama", "Dersin devam durumunu kaydedin ve yoklama kayıtlarını izleyin."],
      ["Canlı dersler", "Canlı ders planlarını ve ilgili oturumları takip edin."],
      ["Canlı ders odası", "Yetkili olduğunuz canlı ders oturumuna katılın."],
      ["Görevlerim ve nöbet", "Size atanan görev ve nöbetleri takip edin."],
    ] },
    { title: "İçerik ve soru üretimi", summary: "Dersin bütün hazırlığı aynı çalışma alanında.", items: [
      ["Konu anlatımı", "Ders içeriklerini ve materyallerini yönetin."],
      ["İçerik stüdyosu", "İçerik hazırlama ve düzenleme araçlarını kullanın."],
      ["Soru bankası", "Soru kayıtlarını konu ve ilgili ölçütlerle yönetin."],
      ["Soru stüdyosu", "Soru hazırlama ve düzenleme işlemlerini yürütün."],
      ["Toplu soru yükleme", "Desteklenen soru aktarımıyla çok sayıda soruyu içe alın."],
      ["Soru iş akışı", "Soru hazırlama ve değerlendirme sürecini izleyin."],
      ["Soru kutusu", "Öğrencilerin ilettiği soruları inceleyin ve cevaplayın."],
      ["Kütüphane", "Yetkili olduğunuz kütüphane kaynaklarına ulaşın."],
    ] },
    { title: "Ödev, sınav ve değerlendirme", summary: "Her çalışmanın sonucunu görünür kılın.", items: [
      ["Ödevler", "Ödev oluşturun, öğrencilere atayın ve teslim durumlarını takip edin."],
      ["Teslim merkezi", "Öğrenci teslimlerini inceleyin ve değerlendirin."],
      ["Sınavlar", "Sınavları hazırlayın ve yetkili olduğunuz sınav süreçlerini yönetin."],
      ["Sınav çalışma alanı", "Sınav hazırlama ve düzenleme araçlarını kullanın."],
      ["Not girişi", "Öğrencilere ait değerlendirme notlarını kaydedin."],
      ["Deneme sınavları", "Deneme sınavlarını ve sonuçlarını takip edin."],
      ["Öğrenci sınavları", "Öğrencilere ait sınav kayıtlarını inceleyin."],
      ["Raporlar", "Ders ve öğrenci gelişimine ait raporları görüntüleyin."],
    ] },
    { title: "Görüşme ve iletişim", summary: "Öğrenci ve veliyle kurumun belirlediği kapsamda.", items: [
      ["Görüşme onayları", "Size yönlendirilen görüşme taleplerini değerlendirin."],
      ...communication.items,
    ] },
  ] },
  veli: { scope: "Veli yalnızca hesabına bağlı çocukların bilgilerini görür. Finans, rehberlik, servis ve yemekhane alanları kurumun ilgili modülü açmasına bağlıdır.", groups: [
    { title: "Çocuklarınızın eğitim hayatı", summary: "Her çocuk için ayrı bilgi, tek hesapta.", items: [
      ["Veli panosu ve çocuklarım", "Hesabınıza bağlı çocukları seçin ve her birinin günlük özetini görün."],
      ["Ders ve devam takibi", "Çocuğunuzun ders akışını ve devamsızlık kayıtlarını inceleyin."],
      ["Sınav sonuçları", "Paylaşılan sınav notlarını ve sonuçlarını takip edin."],
      ["Akademik özet", "Ödev, ders ve akademik gelişim bilgilerine ulaşın."],
      ["Haftalık rapor", "Çocuğunuzun haftalık gelişim ve devam özetini inceleyin."],
      ["Kütüphane", "Size açılan kütüphane bilgilerine ulaşın."],
    ] },
    { title: "Talepler ve rehberlik", summary: "Kurumla olan iletişiminiz kayıt altında.", items: [
      ["Geri bildirim", "Kurumla ilgili geri bildirimlerinizi iletin."],
      ["Görüşmeler", "Görüşme talebi oluşturun ve görüşme durumunu takip edin."],
      ["Mazeret bildirimi", "Çocuğunuzun devamsızlığı için mazeret talebini iletin."],
      ["Taleplerim", "Gönderdiğiniz taleplerin yanıt ve durumlarını görün."],
      ["Rehberlik", "Rehberlik randevusu talep edin ve sizinle paylaşılan çocuk özetini inceleyin."],
    ] },
    { title: "Ödeme ve kurum hizmetleri", summary: "Günlük ihtiyaçların bilgisi yanınızda.", items: [
      ["Ödemeler", "Çocuğunuza ait taksit, ödeme ve kalan borç bilgisini görün."],
      ["Makbuz arşivi", "Hesabınıza açılan ödeme makbuzlarına ulaşın."],
      ["Servis takip", "Çocuğunuza bağlı servis ve sefer durumunu kurumun paylaştığı kapsamda takip edin."],
      ["Yemek menüsü", "Haftalık yemek programını ve paylaşılan beslenme bilgilerini görün."],
    ] }, communication,
  ] },
  ogrenci: { scope: "Öğrenci kendi eğitim kayıtlarına ve kurumun kendisiyle paylaştığı içeriklere erişir. Başka öğrencilerin kayıtlarını yönetemez.", groups: [
    { title: "Ders ve günlük plan", summary: "Bugünün programından sonraki hedefine.", items: [
      ["Ana sayfa", "Derslerini, çalışmalarını ve sana ait güncel bilgileri birlikte gör."],
      ["Ders programı", "Haftalık derslerini ve saatlerini takip et."],
      ["Çalışma planım", "Kişisel çalışma programını ve planlanan görevlerini izle."],
      ["Canlı dersler", "Sana açılan canlı ders oturumlarına katıl."],
      ["Devamsızlık", "Kendi devam ve devamsızlık kayıtlarını gör."],
      ["QR yoklama", "Aktif ve geçerli yoklama oturumunun QR koduyla devam işlemini yap."],
      ["Ödevler", "Atanan ödevleri incele, çalışmanı teslim et ve durumunu takip et."],
    ] },
    { title: "Öğrenme ve soru çözümü", summary: "İçeriği keşfet, öğrendiğini dene.", items: [
      ["Konu anlatımı ve içerik detayları", "Paylaşılan ders materyallerini ve konu içeriklerini incele."],
      ["Soru bankası", "Sana açılan soru havuzunda sorulara ulaş."],
      ["Soru pratiği", "Soruları çöz ve ilgili çözüm sonucunu takip et."],
      ["Soru sor", "Sorularını öğretmenine soru kutusu üzerinden ilet."],
      ["Yanlışlarım", "Yanlış cevaplarını incele ve tekrar çalışmana yön ver."],
      ["Favoriler", "Kaydettiğin içeriklere yeniden ulaş."],
      ["Notlarım", "Öğrenme sırasında tuttuğun notları takip et."],
      ["Kütüphane", "Kurumun sana açtığı kütüphane kaynaklarını incele."],
    ] },
    { title: "Sınav ve gelişim", summary: "İlerlemenin bütün ayrıntıları.", items: [
      ["Sınavlarım", "Sana atanan sınavları ve ilgili sınav işlemlerini takip et."],
      ["Deneme sınavları", "Denemelerini ve deneme sonuçlarını gör."],
      ["Sınav sonuçlarım", "Notlarını ve değerlendirme sonuçlarını incele."],
      ["Rozetler", "Hesabında gösterilen başarı rozetlerini takip et."],
      ["Rehberlik", "Rehberlik randevusu iste ve sana atanan envanterleri tamamla."],
      ["Yemekhane", "Kurumun paylaştığı haftalık yemek programını gör."],
    ] }, communication,
  ] },
  muhasebe: { scope: "Muhasebe kullanıcısı kendisine tanımlanan finans ve şube kapsamıyla çalışır. Kurumun rol, yetki ve personel onayı yönetimi bu rolün genel yetkisi değildir.", groups: [...finance, { ...communication, items: [communication.items[0], communication.items[2]] }] },
  personel: { scope: "İdari personelin işlemleri atanan birim, modül ve izinlerle sınırlıdır. Yöneticiye özel finans/personel onayları, rol yönetimi, yetki matrisi ve kurum veri indirme bu role otomatik açılmaz.", groups: [
    { title: "Günlük operasyon ve ekip", summary: "Kurumun günlük işlerini birlikte yürütün.", items: [
      ["Operasyon", "Günlük operasyon kayıtlarını ve kurum işlerini takip edin."],
      ["Görev merkezi", "Yetkiniz kapsamındaki görevleri oluşturun, atayın ve izleyin."],
      ["Nöbet oluşturma ve tüm nöbetler", "Yetkili olduğunuz nöbet planlarını ve görevlendirmeleri yönetin."],
      ["Ders programı", "Kurumun ders programını yetkiniz kapsamında inceleyin ve düzenleyin."],
      ["Öğretmen programı", "Öğretmenlerin ders dağılımını takip edin."],
      ["Personel kaydı", "İzin verilen personel kayıt işlemlerini yürütün."],
      ["Personel / İK", "Size açılmış personel ve insan kaynakları işlemlerini yürütün."],
      ["Organizasyon birimleri", "Atanan kapsam içindeki birim bilgilerini takip edin."],
    ] },
    { title: "Belgeler ve kurum hizmetleri", summary: "Operasyonun tamamlayıcı alanları.", items: [
      ["Sözleşme ve formlar", "Yetkiniz kapsamındaki form ve sözleşme kayıtlarıyla çalışın."],
      ["İdari kayıtlar", "İdari işlem kayıtlarını oluşturun ve takip edin."],
      ["Belge merkezi", "Size açılan kurum belgelerine ve belge işlemlerine ulaşın."],
      ["Kütüphane", "Yetkili olduğunuz kütüphane kayıtlarını takip edin."],
      ["Servis takip", "İzin verilen servis, rota ve sefer bilgilerini yönetin."],
      ["Yemekhane", "Yetkiniz kapsamında yemek programına ve menü işlemlerine ulaşın."],
      ["Raporlar", "Size açılan kurum ve operasyon raporlarını inceleyin."],
    ] },
    { title: "Talepler ve iletişim", summary: "Kurumun iş akışını tamamlayın.", items: [
      ["Şifre talepleri", "Yetkiniz kapsamındaki şifre sıfırlama taleplerini takip edin."],
      ["Görüşme akışı", "Kurumun görüşme taleplerini ve planlanan görüşmelerini izleyin."],
      ["Duyuru yönetimi", "Yetkiniz kapsamındaki kurum duyurularını düzenleyin."],
      ["Mesajlar", "Yetkili olduğunuz kişilerle kurum içi yazışmalarınızı yürütün."],
      ["Ayarlar", "Hesabınıza açılan tercihleri düzenleyin."],
    ] },
  ] },
  rehberlik: { scope: "Rehberlik, rehberlik branşlı öğretmenin ayrı çalışma alanıdır. Öğrenci dosyaları ve görüşme bilgileri yetkilendirilmiş kapsam içinde görüntülenir.", groups: [
    { title: "Öğrenci dosyası ve takip", summary: "Gelişimi bütün yönleriyle izleyin.", items: [
      ["Vaka merkezi", "Takip edilen öğrencileri ve öncelikli durumları birlikte görün."],
      ["Öğrenci dosyası", "Yetkili olduğunuz öğrenciye ait rehberlik bilgilerini inceleyin."],
      ["Risk takibi", "Risk durumlarını, incelenen kayıtları ve takip gerektiren öğrencileri izleyin."],
      ["Hedefler ve takip tarihleri", "Öğrenci hedeflerini ve sonraki takip adımlarını kaydedin."],
      ["Görüşmeler", "Görüşme kayıtlarını, notlarını ve takip bilgilerini yönetin."],
    ] },
    { title: "Randevu, plan ve envanter", summary: "Her öğrencinin ihtiyacına göre ilerleyin.", items: [
      ["Randevular", "Öğrenci ve veli taleplerini onaylayın veya reddedin; tamamlanan görüşmeleri işaretleyin."],
      ["Müsaitlik", "Görüşme için uygun gün ve saatleri düzenleyin."],
      ["Çalışma programı", "Öğrenciye çalışma blokları ve planlar hazırlayın; şablonları kullanın."],
      ["Envanterler", "Öğrenciye envanter atayın ve tamamlanan yanıtları takip edin."],
      ["Raporlar", "Görüşme, randevu ve sınıf bazındaki rehberlik özetlerini inceleyin."],
      ["Kütüphane", "Rehberlik çalışma alanına açılmış kaynaklara ulaşın."],
      ["Mesajlar ve ayarlar", "Yetkili iletişiminizi ve hesabınızın tercihlerini yönetin."],
    ] },
  ] },
  "sube-muduru": { scope: "Şube müdürü yönetici çalışma alanını kullanır; veri erişimi kendi şubesine kilitlidir. Şubeler arası karşılaştırma, yeni şube oluşturma ve kurum genelindeki işlemler ayrıca yetki gerektirir.", groups: admin.map(group => ({ ...group, items: group.items.filter(([title]) => !["Şube kaydı", "Şube karşılaştırma", "Verilerimi indir"].includes(title)) })) },
  yemekhane: { scope: "Yemekhane kullanıcısının çalışma alanı haftalık yemek programıdır. Öğrenci, finans veya kurum yetki yönetimi bu rolün kapsamına girmez.", groups: [
    { title: "Haftalık yemek programı", summary: "Her öğünün bilgisi düzenli ve erişilebilir.", items: [
      ["Hafta seçimi", "İlgili haftanın yedi günlük yemek programını görüntüleyin."],
      ["Kahvaltı ve öğle yemeği", "Gün ve öğün bazında yemekleri ve servis saatlerini düzenleyin."],
      ["Menü düzenleme", "Seçtiğiniz öğüne yemekleri ve açıklamaları ekleyin; programı kaydedin."],
      ["Besin değerleri", "Kalori, protein, karbonhidrat, yağ ve lif bilgilerini girin."],
      ["Alerjen bilgisi", "Menüdeki alerjenleri ve ilgili açıklamaları kaydedin."],
      ["Planlama özeti", "Planlanan ve eksik öğünleri, haftalık beslenme ve alerjen özetini görün."],
    ] },
  ] },
  "servis-soforu": { scope: "Aktif şoför kaydı bulunan idari kullanıcı mobilde şoför ekranına yönlendirilir. Yalnızca kendisine atanmış rotalar ve rota öğrencileriyle çalışır; konum paylaşımı cihaz iznine bağlıdır.", groups: [
    { title: "Rota ve sefer", summary: "Atanan servisin günlük akışı.", items: [
      ["Bugünkü rotalar", "Size atanmış güncel servis rotalarını seçin ve inceleyin."],
      ["Öğrenci alım listesi", "Seçili rotanın öğrencilerini ve alım bilgilerini görün."],
      ["Sefer yönetimi", "Seferi başlatın ve yolculuğun durumunu takip edin."],
      ["Öğrenci durumları", "Öğrencinin servis durumunu ve okula ulaşmasını kaydedin."],
      ["Bugün binmeyecek bilgisi", "Rotadaki öğrencinin o gün servise binmeyeceği bilgisini takip edin."],
      ["Konum paylaşımı", "Aktif sefer sırasında cihaz izniyle servis konumunu paylaşın."],
      ["Bildirimler", "Rota ve seferle ilgili paylaşılan bildirimleri görün."],
      ["Sefer tamamlama", "Tamamlanan yolculuğun durumunu güncelleyin."],
    ] },
  ] },
  "platform-yoneticisi": { scope: "Platform yöneticisi SchoolAsist işletim ekibine ait ayrı roldür; kurum kayıtlarıyla gelen bir kullanıcı yetkisi değildir.", groups: [
    { title: "Kurum yaşam döngüsü", summary: "Başvurudan aktif kullanıma kadar.", items: [
      ["Platform özeti", "Platformun kurum ve kullanım göstergelerini inceleyin."],
      ["Kurumlar ve başvurular", "Kurum başvurularını inceleyin, onaylayın veya reddedin."],
      ["Kurum erişimi", "Kurumun kullanımını etkinleştirin veya engelleyin; kurumun kullanıcı erişimini kontrol edin."],
      ["Paketler", "Platform paketlerini ve paket tanımlarını yönetin."],
      ["Faturalama ve abonelik", "Kurumların abonelik ve faturalama kayıtlarını takip edin."],
      ["Limitler", "Kurumların kullanım limitlerini ve kaynak sınırlarını yönetin."],
      ["Kurum özelleştirme", "Kurumlara ait görünüm ve yapılandırma seçeneklerini düzenleyin."],
    ] },
    { title: "İşletim ve destek", summary: "Platformun günlük kontrol alanı.", items: [
      ["Sistem", "Platformun sistem yapılandırmalarını ve durumunu takip edin."],
      ["AI yönetimi", "Mevcut AI entegrasyonlarının platform yapılandırma alanını yönetin."],
      ["Log merkezi", "Platform işlem kayıtlarını ve denetim bilgilerini inceleyin."],
      ["Destek", "Müşteri numarasıyla ilişkilendirilen destek kayıtlarını ve kurum taleplerini yönetin."],
      ["Ayarlar", "Platform hesabınıza açılan tercihleri düzenleyin."],
    ] },
  ] },
}
