export const roles = [
  { id: "yonetici", name: "Yönetici", title: "Büyük resmi görün.", accent: "Her detaya ulaşın.", description: "Şubeler, ekipler ve kurumun günlük akışı elinizin altında.", screen: "Kurum özeti", features: ["Kurumun günlük akışı", "Ekip ve öğrenci yönetimi", "Raporlar ve finans takibi"] },
  { id: "ogretmen", name: "Öğretmen", title: "Derse odaklanın.", accent: "Akış hazır.", description: "Plan, yoklama, ödev ve gelişim bir arada.", screen: "Bugünün dersleri", features: ["Ders programı ve yoklama", "Ödev ve sınav takibi", "Öğrenci gelişimi"] },
  { id: "veli", name: "Veli", title: "Günün her adımı.", accent: "İçiniz daha rahat.", description: "Çocuğunuzun derslerini, devamını ve bildirimlerini takip edin.", screen: "Öğrenci gelişimi", features: ["Devam ve ders bilgileri", "Kurumdan duyurular", "Ödev ve gelişim takibi"] },
  { id: "ogrenci", name: "Öğrenci", title: "Sıradaki hedefin.", accent: "Önünde.", description: "Derslerini planla, ödevlerini takip et, gelişimini gör.", screen: "Derslerim", features: ["Kişisel ders programı", "Ödevler ve duyurular", "Sınav sonuçları"] },
  { id: "muhasebe", name: "Muhasebe", title: "Her hareket net.", accent: "Finans kontrol altında.", description: "Tahsilat, taksit ve gider takibi aynı çalışma alanında.", screen: "Finansal görünüm", features: ["Tahsilat ve ödeme takibi", "Geciken ödemeler", "Finansal raporlar"] },
  { id: "personel", name: "İdari Personel", title: "Ekibin akışı.", accent: "Birlikte ilerler.", description: "Size verilen görevler ve kurum duyuruları aynı yerde.", screen: "Günlük akış", features: ["Görev ve duyurular", "Günlük iş takibi", "Role göre erişim"] },
  { id: "rehberlik", name: "Rehberlik", title: "Her öğrencinin yolculuğu.", accent: "Özenle takipte.", description: "Görüşmeler, çalışma planları, envanterler ve öğrenci gelişimi.", screen: "Vaka merkezi", features: ["Öğrenci dosyası ve risk takibi", "Randevu ve görüşmeler", "Çalışma planı ve envanterler"] },
  { id: "sube-muduru", name: "Şube Müdürü", title: "Şubenizin bütün akışı.", accent: "Kontrolünüzde.", description: "Yönetim araçları, kendi şubenizin güvenli veri kapsamında.", screen: "Şube özeti", features: ["Şube operasyonu", "Ekip ve akademik yönetim", "Şubeye ait finans ve raporlar"] },
  { id: "yemekhane", name: "Yemekhane", title: "Her öğün planlı.", accent: "Her ayrıntı görünür.", description: "Haftalık menü, besin değerleri ve alerjen bilgileri bir arada.", screen: "Haftalık yemek programı", features: ["Haftalık menü", "Öğün ve besin değerleri", "Alerjen bilgisi"] },
  { id: "servis-soforu", name: "Servis Şoförü", title: "Her yolculuk.", accent: "Takip altında.", description: "Size atanan rotalar, öğrenciler ve sefer durumu mobilde.", screen: "Bugünkü rota", features: ["Atanan rotalar", "Öğrenci alım listesi", "Sefer ve konum paylaşımı"] },
] as const
export type RoleId = typeof roles[number]["id"]
