import { LegalDocument } from "@/components/site/legal-document"
const sections = [
  { id: "giris", title: "1. Giriş", content: "Bu sayfa SchoolAsist web sitesindeki kurum başvurusu, hesap erişimi ve destek taleplerinde paylaşılan bilgilerin kullanımını açıklar. Veri sorumlusu Maydanoz Yazılım’dır. Ayrıntılı veri işleme bilgileri ve haklarınız için KVKK aydınlatma metnini inceleyin." },
  { id: "kullanim", title: "2. Verilerin kullanımı", content: "Başvuruda paylaştığınız kurum ve yetkili bilgileri, başvurunuzun değerlendirilmesi ve kurum hesabının oluşturulması için kullanılır. E-posta adresiniz doğrulama, başvurunun alındığı ve yönetici onayı bildirimleri için gereklidir. Destek talepleri, müşteri numarasıyla ilgili kurumun destek sürecine yönlendirilir." },
  { id: "saklama", title: "3. Saklama", content: "Başvuru ve destek kayıtları hizmetin yürütülmesi ve ilgili yükümlülüklerin karşılanması amacıyla saklanır. Doğrulama bağlantıları ve geçici parolalar sürelidir. E-posta kuyruğundaki gönderim içeriği, gönderim tamamlandığında veya geçersiz olduğunda temizlenir." },
  { id: "guvenlik", title: "4. Güvenlik", content: "Kurum erişimi platform yöneticisinin onayından sonra açılır. Kullanıcıların erişimi kurum durumuna ve tanımlanan yetkilere bağlıdır. Geçici parola ilk girişte değiştirilmelidir. Destek mesajlarına parola veya öğrencilere ait özel bilgileri eklemeyin." },
  { id: "hesap-silme", title: "5. Hesap ve kurum silme", content: "Verileriniz hesabınızı kullandığınız sürece saklanır. Hesabınızı uygulama içinden parolanızla yeniden doğrulayıp onaylayarak silebilirsiniz. Silme talebinden sonra 30 günlük iptal edilebilir bir bekleme süresi başlar; süre dolunca işlem otomatik ve kalıcı tamamlanır. 30 gün sonunda profil bilgileriniz, mesajlarınız, bildirimleriniz, dosyalarınız ve uygulama tercihleriniz kalıcı olarak silinir; oturum ve bildirim kayıtlarınız iptal edilir. Finans ve eğitim kayıtlarındaki kişisel tanımlayıcılarınız silinir; geriye kalan tutar/sonuç satırları sizi tanımlamayan anonim kayıtlara dönüşür. Kurum silme, kurum yöneticisinin talebi ve platform onayıyla yapılır." },
  { id: "iletisim", title: "6. İletişim", content: "Kişisel veri başvurularınız ve gizlilikle ilgili sorularınız için Maydanoz Yazılım’a info@schoolasist.com adresinden ulaşabilirsiniz. Telefon: 0850 242 84 25." },
]
export default function Page() { return <LegalDocument kind="privacy" title="Gizlilik Politikası" introduction="Bilgilerinizin kullanımı, saklanması ve başvuru yollarınız." sections={sections} /> }
